In [ ]:
from google.colab import files
uploaded = files.upload()

Saving hw_200.csv to hw_200 (1).csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('hw_200.csv') # replace with
df.head()    #shows first 5 rows

   Index   Height(Inches)"   "Weight(Pounds)"
0      1             65.78             112.99
1      2             71.52             136.49
2      3             69.40             153.03
3      4             68.22             142.34
4      5             67.79             144.30

In [ ]:
df.info()     #see column names & data types
df.describe() # see stats for numeric columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Index           200 non-null    int64
 1   Height(Inches)  200 non-null    float64
 2   Weight(Pounds)  200 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 4.8 KB

            Index  Height(Inches)  Weight(Pounds)
count  200.000000      200.000000      200.000000
mean   100.500000       67.949800      127.221950
std     57.879185        1.940363       11.960959
min      1.000000       63.430000       97.900000
25%     50.750000       66.522500      119.895000
50%    100.500000       67.935000      127.875000
75%    150.250000       69.202500      136.097500
max    200.000000       73.900000      158.960000

In [ ]:
# Example: find avrage height per gender (replace columns names)
df_sorted = df.sort_values(by='Height(Inches)')
df_sorted.head()

     Index  Height(Inches)  Weight(Pounds)
97      98           63.43          123.10
22      23           63.48           97.90
109    110           63.84          127.19
39      40           64.05          106.71
155    156           64.13          106.11

In [ ]:
df.columns = df.columns.str.strip().str.replace('"', '')
# replace 'Height(Inches)' with a numeric column in your CSV
tall_people = df[df['Height(Inches)'] > 70]
tall_people

     Index  Height(Inches)  Weight(Pounds)
1        2           71.52          136.49
7        8           70.01          136.46
15      16           71.09          140.00
18      19           71.23          137.90
26      27           70.84          142.42
33      34           70.60          136.22
34      35           71.80          140.10
52      53           70.27          125.48
55      56           70.18          147.89
56      57           70.41          155.90
64      65           70.81          135.32
71      72           70.84          134.02
82      83           70.05          155.38
87      88           70.09          131.59
88      89           70.18          121.12
91      92           70.24          141.49
92      93           71.49          140.61
94      95           70.06          133.46
95      96           70.56          131.80
111    112           70.05          127.61
112    113           70.19          131.64
114    115           70.01          122.04
129    130           70.24          133.98
131    132           71.23          130.70
134    135           71.10          128.14
138    139           73.90          151.39
154    155           72.44          136.74
156    157           70.98          158.96
158    159           72.02          138.78
174    175           73.83          139.30
190    191           70.19          144.99
199    200           71.39          127.88

In [ ]:
# Example: find average height per gender (replace columns names)
if 'Gender' in df.columns:
    avg_height = df.groupby('Gender')['Height(Inches)'].mean()
    print(avg_height)

In [ ]:
df_sorted = df.sort_values(by='Height(Inches)')
df_sorted.head()

     Index  Height(Inches)  Weight(Pounds)
97      98           63.43          123.10
22      23           63.48           97.90
109    110           63.84          127.19
39      40           64.05          106.71
155    156           64.13          106.11

In [ ]:
print('Talest person is') , df_sorted.iloc[-1]['Height(Inches)']

Talest person is

(None, np.float64(73.9))